### ISSUE TITLE
okta-scim-flask-example - 403 Forbidden

### ISSUE THREAD

**Issue by ryguy77** [oktadev/okta-blog#1188]
I am working with the Flask SCIM Server and I am getting an error when attempting to enable the SCIM settings in Okta. 
I have the python app setup and ngrok configured with a paid account. 
I have tried the default access token and configured access token and still receive the same error.  
GET /scim/v2/Users             403 Forbidden 

Can you please help as I am using this as a troubleshooting step for our issue with SCIM provisioning in AWS.

**Comment by mraible** [comment]
Hello @ryguy77,

Can you please post this question to the [Okta Developer Forums](https://devforum.okta.com/)? That way, more people will see it and should be able to help you. If you could provide a link to the tutorial you're using, that would be great too.

Thanks,

Matt
