### ISSUE TITLE
Tags can wrap when they have a dash in them

### ISSUE THREAD

**Issue by mraible** [oktadev/okta-blog#1255]
We might want to add `white-space: nowrap` or something similar.

![image](https://user-images.githubusercontent.com/17892/187509774-e0bfed4f-2747-44a6-8114-9ccdb58799ab.jpeg)

**Comment by deepu105** [comment]
oh yes, also probably should just limit showing first 4 or 5 tags, what do you think?

**Comment by deepu105** [comment]
the PR fixes whitespace and wraps the tags when they overflow into another line
