### ISSUE TITLE
Doc heading links to `H3`s will automatically update to the parent `H2` fragment

### ISSUE THREAD

**Issue by bdemers** [oktadev/okta-blog#977]
You can manually navigate and click on the header (or go directly to the page via the link):
https://developer.okta.com/docs/guides/implement-grant-type/clientcreds/main/#base64-encode-the-client-id-and-client-secret

After the browser address bar is automatically updated to the parent `h2`, in the case of the link above `#flow-specifics`.

I'm guessing this has to do with the right navigation ("On This Page"), trying to find the closest heading.

https://user-images.githubusercontent.com/99954/143927864-2edc8557-9cf5-4fb8-816f-f5f7a482bbb4.mov

What _should_ happen, is the right navigation is updated to show the parent `H2` title, but the address bar is NOT changed.

NOTE: There is also a padding/margin related issue where the heading appears to be displayed _under_ the page header

**Comment by mraible** [comment]
Should this go in the developer docs repository?

**Comment by bdemers** [comment]
I have no idea why I created this here, must have been a long day...
I'll move it over

**Comment by bdemers** [comment]
Actually, it looks like it's been fixed
